version: '4.47.0'

services:
  postgres:
    container_name: api_curso_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api_curso